### ISSUE TITLE
Log `confirm` topic messages

### ISSUE THREAD

**Issue by trym-b** [nlnwa/hermetic#3]
**Motivation**

The current design proposal only validates the entries in the `reject` topic, but the messages sent to the `confirm` topic might still be of interest.

**Feature**

Logging at least the relevant results from the `confirm` topic could be helpful when debugging.

**Comment by maeb** [comment]
I suggest adding a third command to hermetic that listens to the confirm topic and logs the relevant messages.

**Comment by maeb** [comment]
Closed by #44
